[package]
name = "futures-lite"
# When publishing a new version:
# - Update CHANGELOG.md
# - Create "v2.x.y" git tag
version = "2.3.0"
authors = [
  "Stjepan Glavina <stjepang@gmail.com>",
  "Contributors to futures-rs",
]
edition = "2021"
rust-version = "1.60"
description = "Futures, streams, and async I/O combinators"
license = "Apache-2.0 OR MIT"
repository = "https://github.com/smol-rs/futures-lite"
homepage = "https://github.com/smol-rs/futures-lite"
documentation = "https://docs.rs/futures-lite"
keywords = ["asynchronous", "futures", "async"]
categories = ["asynchronous", "concurrency"]
exclude = ["/.*"]

[features]
default = ["race", "std"]
std = ["alloc", "fastrand/std", "futures-io", "parking"]
alloc = []
race = ["fastrand"]

[dependencies]
fastrand = { version = "2.0.0", optional = true, default-features = false }
futures-core = { version = "0.3.5", default-features = false }
futures-io = { version = "0.3.5", optional = true }
memchr = { version = "2.3.3", optional = true }
parking = { version = "2.2.0", optional = true }
pin-project-lite = "0.2.0"

[dev-dependencies]
spin_on = "0.1.0"
waker-fn = "1.0.0" # used in doctests
